# Generated by Django 5.0.7 on 2025-08-20 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logregs_app', '0005_remove_expense_description_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logregs_app.customtitle'),
        ),
    ]
